Add init/shutdown tests
cargo-bsp/cargo-bsp pull request #41
Opened 2023-04-27 10:56 UTC by KatKlo

2023-04-27 12:57 UTC, KatKlo commented on src/communication/connection.rs
> +    pub fn memory() -> (Connection, Connection) {
to jest przekopiowane z rust analyzera 1:1, w drugim PR ten moduł jest usunięty i tak

2023-04-27 12:58 UTC, KatKlo commented on src/communication/connection.rs
> +            break match self.receiver.recv() {
jak wyżej

2023-04-27 22:49 UTC, KatKlo commented on src/server/server_run.rs
> +            }
fajny pomysł z tymi enumami, użyje ich

2023-04-27 23:01 UTC, KatKlo commented on src/server/main_loop.rs
> +            add_notif: bool,
że klient ma wysłać shutdown request/notification

2023-04-27 23:08 UTC, KatKlo commented on src/server/main_loop.rs
> +        }
Starałam się dać takie nazwy testów aby opisywały jaki case sprawdza, jeżeli uważasz że przydałby się dodatkowy komentarz to mogę go umieścić, jednak wydaje się mi on zbędny. 
Wydaje mi się również, że takie wyabstrahowanie logiki testów tego samego typu pozwoliło uniknąć sporo copy-paste, co moim zdaniem sprawia że kod jest bardziej przyjemny do czytania. Jeżeli jednak Twoim zdaniem jest to bardzo nieczytelne to mogę to oczywiście zmienić

2023-04-27 23:09 UTC, KatKlo commented on src/bin/server.rs
>  #[cfg(not(debug_assertions))]
tak zrobię w takim razie. 
Na potrzeby debugu zostawię także te wypisywane na terminal oraz zapisywane w pliku w naszym projekcie - bywają przydatne

2023-05-05 10:04 UTC, agluszak requested changes

2023-05-05 10:04 UTC, agluszak commented on src/test_utils.rs
> +    pub fn new(channel_works_ok: bool, func_returns_ok: bool) -> Self {
to też proponuję przerobić na enumy dla czytelności

2023-05-06 20:23 UTC, agluszak approved these changes

2023-05-08 12:04 UTC, agluszak approved these changes

2023-05-08 19:47 UTC, merged