Implement CreateCommand trait with target kinds and features
cargo-bsp/cargo-bsp pull request #57
Opened 2023-05-23 16:36 UTC by PBundyra

2023-06-12 11:21 UTC, agluszak requested changes
niezbyt mi się ten kod podoba, jakaś logika spaghetti się z tego robi

ale dobrze że są testy przynajmniej

2023-06-12 11:21 UTC, agluszak commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +                    .map(|f| f.0.clone())
```suggestion
                    .cloned()
```

2023-06-12 11:21 UTC, agluszak commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +                    format!("Target {:?} not found", id),
czy to się nie będzie dwa razy wyświetlać?

2023-06-12 11:21 UTC, agluszak commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +        get_target_details: impl Fn(&BuildTargetIdentifier) -> Option<TargetDetails>,
dość mocno mi się nie podoba że ten argument `get_target_details` się tu wszędzie pałęta

2023-06-12 11:21 UTC, agluszak commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +        Ok(cmd)
kod tego i `create_unit_graph_command` jest chyba w każdym przypadku prawie identyczny?

2023-06-12 11:21 UTC, agluszak commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +        Ok(cmd)
dlaczego tu nie ma `cmd.args(self.arguments.clone());`?

2023-06-12 18:34 UTC, PBundyra commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
>  pub trait CreateCommand {
Trait ten pomaga uzyc funkcji: origin_id(), create_unit_graph_command(), create_requested_command() niezaleznie od tego czy dostaniemy compile/run czy test request. Funkcje create_unit_graph_command(), create_requested_command() uzywane sa w Request Handle

2023-06-12 18:39 UTC, PBundyra commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +        Ok(cmd)
Funkcje ```create_unit_graph_command()``` roznia sie uzytymi flagami od tych ```create_requested_command``` Dodatkowo requesty build i test przesylaja liste targetow a run tylko pojedynczy target. Co wiecej do komend odpowiadajacych za wlasciwe build/run czy test binarki dokladamy jeszcze argumenty. Jest wiec pare niuansow ktore odroznia kazde 2 komendy

2023-06-12 18:47 UTC, PBundyra commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +            if t.kind.to_string() == "lib" {
Poprawione

2023-06-12 18:57 UTC, PBundyra commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +const RUN: &str = "run";
Poprawione

2023-06-12 19:11 UTC, PBundyra commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +        Ok(cmd)
Komenda do stworzenia unit graphu nie potrzebuje argumentow ktore przekazujemy do runowanej binarki

2023-06-12 19:12 UTC, PBundyra commented on crates/cargo-bsp/src/cargo_communication/cargo_types/cargo_command.rs
> +        get_target_details: impl Fn(&BuildTargetIdentifier) -> Option<TargetDetails>,
Przekazywanie tej funkcji umożliwia ładne stworzenie testów bez mockowania całego Workspace'a

2023-06-23 16:08 UTC, agluszak approved these changes

2023-07-01 05:14 UTC, merged