Add README
cargo-bsp/cargo-bsp pull request #67
Opened 2023-07-19 09:21 UTC by julia-podrazka

2023-07-19 11:01 UTC, agluszak requested changes

2023-07-19 11:01 UTC, agluszak commented on README.md
> +3. In the directory of the desired Rust project run this script (fill in the SERVER_PATH variable with the directory to the cloned repository):
a może zrobić z tego jakiś skrypt instalujący po prostu?

2023-07-19 14:17 UTC, julia-podrazka commented on README.md
> +3. In the directory of the desired Rust project run this script (fill in the SERVER_PATH variable with the directory to the cloned repository):
Dodałam skrypt, którym można skonfigurować każdy nowy projekt

2023-07-19 15:27 UTC, agluszak requested changes

2023-07-19 15:27 UTC, agluszak commented on configuration_script.sh
> +read PROJECT_PATH
a zamiast takiego wczytywania po prostu użyj $0

2023-07-19 15:27 UTC, agluszak commented on configuration_script.sh
> +SERVER_PATH=$PWD
```suggestion
SERVER_PATH=$PWD/target/debug/server
```

2023-07-19 15:27 UTC, agluszak commented on configuration_script.sh
> +SERVER_PATH=$PWD
swoją drogą pytanie czy chcemy używać debug builda zamiast release'a (ale w sumie czemu nie)

2023-07-19 15:27 UTC, agluszak commented on configuration_script.sh
> +}
```suggestion
}
EOF

```

2023-07-19 15:27 UTC, agluszak commented on configuration_script.sh
> +  "bspVersion": "2.1.0-M4",
```suggestion
  "bspVersion": "2.1.0",
```

2023-07-19 15:27 UTC, agluszak commented on configuration_script.sh
> +  "bspVersion": "2.1.0-M4",
te M-numerki to są wersje bibliotek, a nie protokołu

2023-07-19 15:27 UTC, agluszak commented on configuration_script.sh
> +  "name": "cargobsp",
```suggestion
  "name": "cargo-bsp",
```

2023-07-20 09:29 UTC, julia-podrazka commented on configuration_script.sh
> +SERVER_PATH=$PWD
Możemy w sumie użyć release, wtedy nie będziemy zaśmiecać stderr logami (które na razie wyświetlają się bezpośrednio użytkownikowi). Wydaje mi się że jedyną różnicą u nas między release a debug jest sposób logowania -> przy debug logujemy dodatkowo na stderr i do pliku w ścieżce samego serwera.

2023-07-20 09:34 UTC, julia-podrazka commented on configuration_script.sh
> +cargo build
Done

2023-07-20 09:35 UTC, julia-podrazka commented on configuration_script.sh
> +read PROJECT_PATH
Done

2023-07-20 14:39 UTC, agluszak approved these changes

2023-07-21 11:40 UTC, merged