Add workspaceLibraries, remove Java extension requests
cargo-bsp/cargo-bsp pull request #90
Opened 2023-09-06 15:12 UTC by Toomimi

2023-09-06 16:07 UTC, Toomimi commented on Cargo.toml
> +resolver = "2"
Bo się przy każdej kompilacji wyświetlał warning

2023-09-06 16:07 UTC, Toomimi commented on crates/cargo-bsp/src/server/handlers.rs
> +
Dobrze

2023-09-06 16:55 UTC, KatKlo approved these changes

2023-09-06 23:59 UTC, Toomimi commented on crates/cargo-bsp/src/server/handlers.rs
> +
done

2023-09-07 10:18 UTC, julia-podrazka approved these changes

2023-09-11 11:32 UTC, agluszak requested changes

2023-09-11 11:32 UTC, agluszak commented on Cargo.toml
> +resolver = "2"
newline

2023-09-11 16:48 UTC, merged