Udate bsp_types with bsp4rs
cargo-bsp/cargo-bsp pull request #93
Opened 2023-09-20 09:52 UTC by KatKlo

2023-09-30 18:50 UTC, agluszak requested changes

2023-09-30 18:50 UTC, agluszak commented on crates/bsp_types/src/extensions/rust/mod.rs
> +}
dla takich rzeczy imo lepiej zrobić konstruktor niż pisać From

2023-10-10 15:20 UTC, Toomimi approved these changes

2023-10-10 19:01 UTC, julia-podrazka approved these changes

2023-10-11 11:00 UTC, agluszak approved these changes

2023-10-11 11:03 UTC, agluszak commented on crates/cargo-bsp/src/utils/request_id.rs
> +}
a po co teraz jest osobne bsp_server::RequestId i bsp_types_extensions::RequestId?

2023-10-11 13:47 UTC, agluszak commented on crates/cargo-bsp/src/utils/request_id.rs
> +}
kurczę, a nie dałoby się któregoś pozbyć jakoś?

2023-10-11 13:54 UTC, KatKlo commented on crates/cargo-bsp/src/utils/request_id.rs
> +}
spróbuję

2023-10-11 14:31 UTC, merged